[project]
name = "nmsamplelocations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastadmin>=0.2.22",
    "fastapi>=0.115.12",
    "geoalchemy2>=0.17.1",
]
