name: Code Format
on:
  push:
permissions:
  contents: read
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment - 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Run flake8
        uses: py-actions/flake8@v1
        with:
          ignore: "F401,E501"
          args: "--exit-zero --select=E"
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: psf/black@stable
        with:
          options: "--verbose"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Formatting changes
          branch: ${{ github.head_ref }}